### ISSUE TITLE
"Could not find part of the path" when trying to package Android NDK

### ISSUE THREAD

**Issue by akavel** [0install/0install#130]
I downloaded https://dl.google.com/android/repository/android-ndk-r20b-windows-x86_64.zip, then tried to run the following command, but got an error like below:

```
C:\prog\nnn>0install digest \dnload\nim-etc\android-ndk-r20b-windows-x86_64.zip
Extracting archive...
[====                ] IO error
Could not find part of the path „C:\Users\Mateusz\AppData\Local\Temp\0install-qdnsicgu.lje\android-ndk-r20b\sources\cxx-stl\llvm-libc++\test\std\thread\thread.mutex\thread.mutex.requirements\thread.sharedtimedmutex.requirements\thread.sharedtimedmutex.class\try_lock_until_deadlock_bug.pass.cpp”.
```

I suspect the issue behind this is probably similar as the one I [encountered in 0publish-win when trying to package Go's zip archive](https://github.com/0install/0publish-win/issues/17); the other one seemed to be workable around with the .msi Go installer; is there a similar workaround that could let me have the NDK installed successfully with 0install?

Alternatively, if this is not a problem with the .zip but with accessing the Windows filesystem, I believe [there are ways](https://serverfault.com/questions/232986/overcoming-maximum-file-path-length-restrictions-in-windows) to manipulate paths over MAX_PATH characters on Windows.

**Comment by bastianeicher** [comment]
This is indeed caused by the `MAX_PATH` limitation on Windows.

Zero Install for Windows already supports long file paths, but in order to be able to use this feature the OS needs to be at least Windows 10 version 1607 and the following registry key needs to be set:

Key: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
Name: `LongPathsEnabled`
Value: `0x00000001`

Zero Install [tries to detect this issue and automatically offers to set this registry value](https://github.com/0install/0install-dotnet/blob/master/src/Commands/ProgramUtils.cs#L240), but doesn't seem to catch all cases, like the one you encountered.

I ran the command on my machine with the registry key above set and got:

```
> 0install digest .\android-ndk-r20b-windows-x86_64.zip
Extracting archive...
[====================] Complete
Generating sha1new manifest...
[====================] Complete
sha1new=840ffae5e7d4e8720fe467554a9ffa5266acc7f4
```
