### ISSUE TITLE
Cannot delete 0install.net folder in Windows

### ISSUE THREAD

**Issue by nimmerdk** [0install/0install#141]
HI,

I have a 0install.net folder under my c:\programdata folder and I cannot delete it.

0Install are not installed on the PC anymore and my antivirus reports malicious behavior from that folder so I want it deleted.

I have taken ownership of the folder, but I still cant delete it.

Plz help

/Kim

**Comment by bastianeicher** [comment]
## Option 1: Reinstall and uninstall

When you uninstall Zero Install for Windows it asks "Do you wish to remove all application files from the Zero Install cache?". Selecting "Yes" here will remove this folder.

Since you already uninstalled Zero Install you could temporarily reinstall it and immediately uninstall it again. For example by running this in an Admin PowerShell:

```powershell
Invoke-WebRequest https://0install.de/files/0install.exe -OutFile 0install.exe
.\0install.exe self deploy --machine
.\0install.exe self remove
```

## Option 2: Reset the ACLs

Alternatively you can reset the ACLs for the directory:
1. Open the directories Properties in Explorer.
2. Open the "Advanced" view on the "Security" tab.
3. Click on "Change Permissions" and then set the "Reset all child object permissions" checkbox.

## Background information

Zero Install sets a "Deny Write" permission entry for "Everyone" on each directory in the cache. This prevents apps from modifying their own files at runtime. Basically it's a fancy way of making the directories "read-only". This permission entry needs to be removed, either through Zero Install's uninstall process or manually as described above, before the directories can be deleted.

Making the cache directories read-only is an important part of Zero Install's functionality, because each directory in the cache is named by the cryptographic hash of its contents. If anything inside a directory changes, intentionally or not, the hash would no longer match.

**Comment by Sckrillo** [comment]
Если вы хотите удалить всю эту директорию без использования Zero Install, вы можете использовать эту командную строку:
icacls C:\Users\Yami\AppData\Local\0install.net\implementations /t /q /c /reset; rm -Recurse C:\Users\Yami\AppData\Local\0install.net\implementations
