### ISSUE TITLE
Installing 0repo and its dependencies (git, git-core, and python) on Mac OSX

### ISSUE THREAD

**Issue by ewa** [0install/0install#160]
Hi,

I'm not sure what's supposed to be filed here, vs. emailed to zero-install-bugs vs. zero-install-dev, so please let me know if this is the wrong place.

I'm relatively new to 0install, and am walking through the example / tutorial material from the website on a MacBook running macOS 10.15.4.  When I try to install the 0repo tool, 0install doesn't know what to do about the "git," "git-core," and maybe "python" dependencies.  Git and Python are both installed on this system through non-0install sources, with the versions and locations shown.  Here's what I get when I try to install 0repo:

```shell
Erics-MacBook-Pro:sims andersoe $    0install add 0repo http://0install.net/tools/0repo.xml
Can't find all required implementations:
- http://0install.net/2007/interfaces/ZeroInstall.xml -> 2.3.11 (sha1new=38db1113baf7ef5a352d406a51231687844098b2)
    http://0install.net/tools/0repo.xml 0.11 requires version 2.3.8..
- http://0install.net/tools/0repo.xml -> 0.11 (sha1new=a6cddf09966e1a58fe3956f868c1eb31f725d30a)
- https://apps.0install.net/devel/git.xml -> (problem)
    git: Unknown Darwin/OS X package
    git-core: Unknown Darwin/OS X package
    http://0install.net/tools/0repo.xml 0.11 requires 'run' command
    No usable implementations:
      sha1new=d3b355aa19b2cebf7d6d4f7b090d20ec66abc920 (1.7.2.5-3): Not compatible with the requested OS type
      sha1new=886961d0c4b894d2fae2c7209577fb617b40bfef (1.7.2.5-3): Not compatible with the requested OS type
      sha1new=edfee8eb96ce0096b5ad2279c5d1c79be5d95856 (1.7.2.5-2): Not compatible with the requested OS type
      sha1new=dd3a3e7b45a695cf9997303151a49c8118912904 (1.7.2.5-2): Not compatible with the requested OS type
      sha1new=c89043aa88c264e0d38186133f1402ccaae2eb88 (1.7.2.5-1): Not compatible with the requested OS type
      ...
- https://apps.0install.net/python/python.xml -> 3.7.6.0 (package:host:python:3.7.6.0)
    python27: Unknown Darwin/OS X package
    python26: Unknown Darwin/OS X package
    python25: Unknown Darwin/OS X package
    python27: Unknown Darwin/OS X package
    python26: Unknown Darwin/OS X package
    python25: Unknown Darwin/OS X package
    python: Unknown Darwin/OS X package
    python: Unknown Darwin/OS X package
    python2: Unknown Darwin/OS X package
    python3: Unknown Darwin/OS X package
    python2.7: Unknown Darwin/OS X package
    python2.6: Unknown Darwin/OS X package
    python2.5: Unknown Darwin/OS X package
    python: Unknown Darwin/OS X package
    python3: Unknown Darwin/OS X package
    python27: Unknown Darwin/OS X package
    python26: Unknown Darwin/OS X package
    python25: Unknown Darwin/OS X package
    python2: Unknown Darwin/OS X package
    python: Unknown Darwin/OS X package
    python: Unknown Darwin/OS X package
    http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.11 requires version 3.4..
    http://0install.net/tools/0repo.xml 0.11 requires version 3.6..
    http://0install.net/tools/0repo.xml 0.11 requires 'run' command
- https://apps.0install.net/utils/gnupg.xml -> 2.2.20 (package:darwin:gnupg:2.2.20:x86_64)
    http://0install.net/2007/interfaces/ZeroInstall.xml 2.3.11 requires 'run' command
    http://0install.net/tools/0repo.xml 0.11 requires 'run' command
Erics-MacBook-Pro:sims andersoe $ which git
/usr/local/bin/git
Erics-MacBook-Pro:sims andersoe $ git --version
git version 2.18.0
Erics-MacBook-Pro:sims andersoe $ which python
/usr/bin/python
Erics-MacBook-Pro:sims andersoe $ python --version
Python 2.7.16
Erics-MacBook-Pro:sims andersoe $ which python3
/usr/local/bin/python3
Erics-MacBook-Pro:sims andersoe $ python3 --version
Python 3.7.6
Erics-MacBook-Pro:sims andersoe $ which python2
/usr/bin/python2
Erics-MacBook-Pro:sims andersoe $ python2 --version
Python 2.7.16
```

**Comment by talex5** [comment]
On macOS, 0install looks for native packages by querying mac-ports and then falls back to a hard-coded list (which doesn't include git):

https://github.com/0install/0install/blob/master/src/zeroinstall/distro_impls.ml#L600

From what I hear, most mac users seem to be using homebrew instead of mac-ports these days, so we should probably add support for that.

As a work-around, you can create `git.xml` file containing:

```xml
<?xml version="1.0"?>
<interface xmlns="http://zero-install.sourceforge.net/2004/injector/interface">
  <name>git</name>
  <summary>fast, scalable, distributed revision control system</summary>
  <feed-for interface='https://apps.0install.net/devel/git.xml'/>
  <implementation id="." local-path="/usr/bin" version="2.18.0">
    <command name="run" path="git"/>
  </implementation>
</interface>
```

and then

```bash
0install add-feed git.xml
```

**Comment by ewa** [comment]
Thanks, that works very well.

I'm interested in looking at the package manager / existing un-packaged file integration.  Do you have any pointers for where to start? (Documentation and/or source)

**Comment by talex5** [comment]
Docs:
- https://docs.0install.net/details/distribution-integration/
- https://docs.0install.net/specifications/feed/#package-implementations

Code:
- https://github.com/0install/0install/blob/master/src/zeroinstall/distro.mli (API)
- https://github.com/0install/0install/blob/master/src/zeroinstall/distro_impls.ml#L568 (Mac impl)

That code is a bit messy (sorry). The basic idea is:

1. Your `method get_package_impls` gets called with the distribution's name of the package.
2. You query the package manager to find what versions are installed and/or available.
3. Call `self#add_package_implementation` to register each one.

Making this more complicated:
1. Mac has two separate package managers (darwin and macports) that are both active.
2. macports is doing some caching to speed things up.
3. The file is huge because it contains one submodule for every supported platform. I should probably split them out into one file per platform.
4. There's some excessive escaping going on with the regular expressions. That could be updated to use the new `{|...|}` syntax.

**Comment by ewa** [comment]
Re 1 and 2:  There's also Fink and Homebrew, and my sense is that Homebrew is the most-used / best-maintained of the four.
