### ISSUE TITLE
Uninstall on OS X?

### ISSUE THREAD

**Issue by tmikaeld** [0install/0install#24]
There seems to be no instructions on how to remove Zero Install after installing the bundle.

**Comment by kritzikratzi** [comment]
why was this closed?

**Comment by afb** [comment]
Well, we don't make the installer program (that would be Apple). But I suppose it could be documented more on the 0install site ? Anyway, the 0install files are all being installed under the `/usr/local` prefix:

```
/usr/local/bin/0alias
/usr/local/bin/0desktop
/usr/local/bin/0install
/usr/local/bin/0launch
/usr/local/bin/0store
/usr/local/bin/0store-secure-add
/usr/local/lib/0install.net/gui_gtk.cmxs
/usr/local/man/man1/0desktop.1
/usr/local/man/man1/0install.1
/usr/local/man/man1/0launch.1
/usr/local/man/man1/0store-secure-add.1
/usr/local/man/man1/0store.1
/usr/local/share/0install.net/unlzma
/usr/local/share/0install.net/unxz
/usr/local/share/appdata/0install.appdata.xml
/usr/local/share/bash-completion/completions/0install
/usr/local/share/bash-completion/completions/0launch
/usr/local/share/doc/0install/COPYING
/usr/local/share/doc/0install/README.md
/usr/local/share/fish/completions/0install.fish
/usr/local/share/fish/completions/0launch.fish
/usr/local/share/locale/de/LC_MESSAGES/zero-install.mo
/usr/local/share/locale/es/LC_MESSAGES/zero-install.mo
/usr/local/share/locale/sv/LC_MESSAGES/zero-install.mo
/usr/local/share/zsh/site-functions/_0install
/usr/local/share/zsh/site-functions/_0launch
```

**Comment by kritzikratzi** [comment]
thanks for the file list! now i can just ```rm``` all of them :) 
after running ```pkgutil --unlink net.0install.pkg``` all the files still remained on my disk. 

imho it would make sense to create a folder /Applications/0install/ that contains an uninstall script that removes the files and deletes the cached libraries/applications.

the entire concept of "installing" anything just feels very foreign on a mac (unless it's for drivers or system services, but those are rare cases).

**Comment by afb** [comment]
No problem. Unfortunately 0install isn't a native mac program - but using gtk+, but maybe you have already discovered that - considering you are uninstalling. But it's not that uncommon to install command-line tools, even on the mac. Otherwise, the need to install is something that 0install (ironically) is trying to avoid... Just that you still need all the requirements, like GTK+ and GnuPG, and still need to move it in place for it to work. So the installer bundle was created to make it easier to get started.

But we do have a non-install package for Darwin (including Mac OS X), available as well:
http://0install.net/tools/0install.xml
