### ISSUE TITLE
Issue running JRE in Mac OS X (10.10.3)

### ISSUE THREAD

**Issue by aeng** [0install/0install#39]
Include jre dependency in feed

```
<requires interface="http://repo.roscidus.com/java/openjdk-jre">
   <environment name="JAVA_HOME" insert="." mode="replace" />
 </requires>
```

Throws same exception when trying to run `0launch http://repo.roscidus.com/java/openjdk-jre`

```
Can't find all required implementations:
- http://repo.roscidus.com/java/openjdk-jre -> (problem)
    No usable implementations:
      sha1new=6b7c9f98bd1d8bec5bbb5ddb41271c862c8e8529 (6.18-1.8.7-2): Not compatible with the requested OS type
      sha1new=3ede8dc4b83dd3d7705ee3a427b637a2cb98d789 (6.18-1.8.7-2): Not compatible with the requested OS type
      sha1new=6cc9f66b968d983904bce5050b2e328c3740462b (6.11-9.1-2): Not compatible with the requested OS type
      sha1new=042663897b1fce617d5bc8c98945adc64e4ef2a9 (6.11-9.1-2): Not compatible with the requested OS type
```

Seems like its redirecting to http://repo.roscidus.com/java/openjdk-6-jre for jre6 version. 
How can I specify in my feed with jre 1.7?

**Comment by talex5** [comment]
It should find Java 7 it if it's installed, but if it isn't then it can't download it as there is no 0install OS X download of Java available.

The error is confusing because it doesn't list unavailable distribution-provided packages, which makes it look like it only considered Java 6 (which does have 0install binaries available).

**Comment by talex5** [comment]
I just tested this on a real OS X system, and it was broken. It seems that native package support on OS X was only enabled if the platform name was "Darwin", but the name is reported as "MacOSX" now. I fixed that. Combined with the recent improvements to diagnostics, it will now also tell you if a native package isn't found, which would have made the problem easier to debug. I also added support for Java 8 while there.

@afb if a package isn't found, it reports the error as missing PackageKit support, e.g.

    Can't find all required implementations:                                     
    - test_feed.xml -> (problem)
        openjdk-9-jre: PackageKit not available: 0install was compiled without D-BUS support

Is PackageKit used on OS X? Maybe we should replace this with something else if not.

**Comment by afb** [comment]
@talex5: I don't think that anyone uses PackageKit on OS X, that would require quite a lot of custom work. In fact, I'm not sure that it even works outside of Linux, with the latest systemd adoptions (like the rest of the GNOME Software) ? I know that FreeBSD is running a much older version of it, at least. There is an (unrelated) Apple framework called "PackageKit", but it is *not* the same as http://packagekit.org

The name (and reason for) "MacOSX" is probably obsolete, so if it helps you can to just use "Darwin" everywhere (but feel free to leave it as-is, for compatibility reasons). I'm not sure if anyone still uses MacPorts (or Fink/deb for that matter), but again it probably doesn't hurt to leave it in either. I suppose that Homebrew integration could be added by someone, since it does have `/usr/local` binaries now.

**Comment by talex5** [comment]
Ah, Apple's PackageKit was probably what was confusing me. I've split PackageKit support into a separate class, which OS X and Windows don't inherit. The message for missing packages is now `%s: Unknown Darwin/OS X package`.
