### ISSUE TITLE
Installation error on Windows

### ISSUE THREAD

**Issue by arc232** [0install/0install#60]
Windows 7 x64

Descripción:
  Stopped working

Firma con problemas:
  Nombre del evento de problema:	CLR20r3
  Firma del problema 01:	zero-install.exe
  Firma del problema 02:	2.13.3.0
  Firma del problema 03:	5988845c
  Firma del problema 04:	System
  Firma del problema 05:	2.0.0.0
  Firma del problema 06:	506c18e6
  Firma del problema 07:	21b6
  Firma del problema 08:	18
  Firma del problema 09:	System.NotSupportedException
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	3082

**Comment by bastianeicher** [comment]
Thanks for reporting this. This error is caused by Zero Install trying to activate support for TLS 1.1 and 1.2 on older .NET Framework versions that do not support it yet. I have fix this here: nano-byte/common@262442c

I will create a new release of Zero Install with this fix soon and post here. Until then you can avoid the problem by updating to .NET Framework 4.7.

**Comment by arc232** [comment]
I had .NET Framework 4.7 installed. After repairing it the error persists.

**Comment by bastianeicher** [comment]
@arc232: I have just released Zero Install for Windows 2.13.6. Please let me know if this fixes your issue.

**Comment by arc232** [comment]
yes this fixed it, thanks

**Comment by bastianeicher** [comment]
Good to hear :)
